inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/bucky/test_equipment/user_operation/user_operation_helper.rb'
    - 'spec/fixtures/**/*'
    - 'spec/test_code/**/*'
    - 'template/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

AbcSize:
  Enabled: false

# Allow method prefix start with "set_" and "get_"
AccessorMethodName:
  Enabled: false

BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'bucky-core.gemspec'
    - 'lib/bucky/core/database/test_data_operator.rb'
    - 'lib/bucky/core/test_core/test_class_generator.rb'

ClassVars:
  Exclude:
    - 'lib/bucky/test_equipment/selenium_handler/webdriver_handler.rb'
    - 'lib/bucky/test_equipment/test_case/abst_test_case.rb'
    - 'lib/bucky/utils/config.rb'
    - 'lib/bucky/tools/lint.rb'

CyclomaticComplexity:
  Enabled: false

# Allow missing top-level documentation comment of class
Documentation:
  Enabled: false

FrozenStringLiteralComment:
  EnforcedStyle: always

GlobalVars:
  AllowedVariables: [$bucky_home_dir, $debug, $job_id, $round]

# Not allow using "->" for multi-line lambdas.
Lambda:
  Enabled: false

LineLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

MethodLength:
  Enabled: false

ModuleLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

PerceivedComplexity:
  Enabled: false

UselessAssignment:
  Exclude:
    - 'lib/bucky/core/test_core/test_result.rb'

ClassLength:
  Max: 110

Lint/UselessAccessModifier:
  Exclude:
    - 'example/**/*'