:test_result_path: './system/test_results/'
:log_path: './system/logs/'
:screen_shot_path: './system/evidences/screen_shots/'
:bucky_error: 'bucky_error'
:test_code_repo: 'https://github.com/hogehoge/fugafuga/'
