:selenium_ip: 'docker_host_ip'  # Default selenium ip. please set ip or 'docker_host_ip'. ip route | awk 'NR==1 {print $3}'
:selenium_port: '4444'     # Default selenium port
:browser: :chrome          # Only chrome
:headless: false
:e2e_parallel_num: 1
:sp_device_name: :iphone
:tablet_device_name: :ipad
:device_name_on_chrome:
  :iphone: 'iPhone X'
  :android: 'Galaxy S5'
  :ipad: 'iPad'
:chromedriver_flags: # If you want to use chromedriver options, please add like below
  # - '--disable-dev-shm-usage'
:user_agent: 'E2ETest (X11; Linux x86_64)'
:driver_read_timeout: 60 # sec
:driver_open_timeout: 60 # sec
:find_element_timeout: 10 # sec